- name: install common tools
  hosts: debian
  tasks:
  - apt:
      name:
      - ack
      - bat
      - btop
      - jq
      - podman
      - tmux
      - vim

- name: install common tools
  hosts: fedora
  tasks:
  - name: install common tools
    dnf:
      name:
      - ack
      - bat
      - btop
      - git-delta
      - jq
      - podman
      - tmux
      - vim
