- name: common
  hosts: centos
  tasks:
  - name: install common tools
    dnf:
      name:
      - git
      - jq
      - podman
      - tmux
      - vim

- name: common
  hosts: debian
  tasks:
  - apt:
      name:
      - ack
      - bat
      - btop
      - curl
      - fzf
      - git
      - golang
      - jq
      - kubernetes-client
      - make
      - podman
      - tmux
      - vim
      - wget

- name: common
  hosts: fedora
  tasks:
  - name: install common tools
    dnf:
      name:
      - ack
      - bat
      - btop
      - curl
      - fzf
      - git
      - git-delta
      - golang
      - helm
      - jq
      - kubernetes-client
      - make
      - podman
      - tmux
      - vim
      - wget

- name: common
  hosts: ubuntu
  tasks:
  - apt:
      name:
      - ack
      - bat
      - btop
      - git
      - jq
      - podman
      - tmux
      - vim
