- name: k3s.io
  hosts: fedora
  tasks:
  - name: install k3s
    shell: |
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik" sh -
      kubectl completion bash > /etc/bash_completion.d/kubectl.sh
      mkdir -p /root/.kube
      cp /etc/rancher/k3s/k3s.yaml /root/.kube/config
  - name: stop k3s service
    systemd:
      name: k3s
      state: stopped
  - name: add localhost registry
    copy:
      src: ./k3s/registries.yaml
      dest: /etc/rancher/k3s/registries.yaml
  - name: start k3s service
    systemd:
      name: k3s
      state: started
  - name: remove kubectl symlink
    shell: if [[ -L /usr/local/bin/kubectl ]]; then rm /usr/local/bin/kubectl; fi
  - name: install ingress-nginx
    shell: |
      helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      kubectl create namespace ingress-nginx
      helm install ingress-nginx ingress-nginx/ingress-nginx --wait \
      --namespace ingress-nginx --set controller.ingressClassResource.default=true
  - name: install kubectx
    shell: |
      cd $(mktemp -d)
      wget https://github.com/ahmetb/kubectx/releases/download/v0.9.5/kubectx_v0.9.5_linux_arm64.tar.gz
      tar xf kubectx_v0.9.5_linux_arm64.tar.gz kubectx
      mv kubectx /usr/local/bin/kc
  - name: install kubens
    shell: |
      cd $(mktemp -d)
      wget https://github.com/ahmetb/kubectx/releases/download/v0.9.5/kubens_v0.9.5_linux_arm64.tar.gz
      tar xf kubens_v0.9.5_linux_arm64.tar.gz kubens
      mv kubens /usr/local/bin/kn
  - name: install k9s
    shell: |
      cd $(mktemp -d)
      wget https://github.com/derailed/k9s/releases/download/v0.27.4/k9s_Linux_arm64.tar.gz
      tar xf k9s_Linux_arm64.tar.gz k9s
      mv k9s /usr/local/bin/
