- name: install k3s
  hosts: fedora
  tasks:
  - name: install k3s
    shell: |
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik" sh -
      kubectl completion bash > /etc/bash_completion.d/kubectl.sh
      mkdir -p /root/.kube
      cp /etc/rancher/k3s/k3s.yaml /root/.kube/config
  - name: stop k3s service
    systemd:
      name: k3s
      state: stopped
  - name: add localhost registry
    copy:
      src: ./k3s/registries.yaml
      dest: /etc/rancher/k3s/registries.yaml
  - name: start k3s service
    systemd:
      name: k3s
      state: started
  - name: remove kubectl symlink
    shell: if [[ -L /usr/local/bin/kubectl ]]; then rm /usr/local/bin/kubectl; fi
  - name: install tools
    dnf:
      name:
      - helm
      - kubernetes-client
  - name: install ingress-nginx
    shell: |
      helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      kubectl create namespace ingress-nginx
      helm install ingress-nginx ingress-nginx/ingress-nginx --wait \
      --namespace ingress-nginx --set controller.ingressClassResource.default=true
  - name: install kubernetes-dashboard
    shell: |
      helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard
      kubectl create namespace kubernetes-dashboard
      helm install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --wait \
      --namespace kubernetes-dashboard --set ingress.enabled=true
      kubectl create serviceaccount admin --namespace kubernetes-dashboard
      kubectl create clusterrolebinding kubernetes-dashboard-admin \
      --clusterrole=cluster-admin --serviceaccount=kubernetes-dashboard:admin
  - name: install kubectx
    shell: |
      cd $(mktemp -d)
      wget https://github.com/ahmetb/kubectx/releases/download/v0.9.4/kubectx_v0.9.4_linux_arm64.tar.gz
      tar xf kubectx_v0.9.4_linux_arm64.tar.gz kubectx
      mv kubectx /usr/local/bin/kc
  - name: install kubens
    shell: |
      cd $(mktemp -d)
      wget https://github.com/ahmetb/kubectx/releases/download/v0.9.4/kubens_v0.9.4_linux_arm64.tar.gz
      tar xf kubens_v0.9.4_linux_arm64.tar.gz kubens
      mv kubens /usr/local/bin/kn
